import { sbInsert } from './_supabase.js';

const ACCESS_KEY = 'bds-v06-test';
const MODEL = process.env.GEMINI_MODEL || 'gemini-flash-latest';

const INTENTS = {
  job: { goal:'Entender qué quería conseguir, resolver, mantener, disfrutar o expresar el comprador con esa compra.', selectionMode:'multi', ontology:['functional outcome','emotional outcome','social outcome','continuity outcome','experience outcome','other','unknown'] },
  trigger: { goal:'Entender qué hizo que la compra ocurriera en ese momento y no después.', selectionMode:'multi', ontology:['event','deadline','urgency','depletion','opportunity','stimulus','recommendation','occasion','other','unknown'] },
  barrier: { goal:'Entender qué podía frenar, retrasar o cambiar la decisión de compra.', selectionMode:'multi', ontology:['price','quality','trust','availability','fit','switching cost','time','uncertainty','other','unknown'] },
  customer_language: { goal:'Capturar palabras o ideas que el cliente realmente haya dicho sobre la compra, problema, deseo o motivo de elección.', selectionMode:'free_text', ontology:['direct quote','clear paraphrase','no remembered customer language'] },
  alternatives: { goal:'Entender qué habría comprado, usado o hecho el cliente si no hubiera elegido este negocio.', selectionMode:'multi', ontology:['same-category alternative','substitute-category alternative','existing product or current solution','DIY/workaround if category-compatible','delay','no purchase','other','unknown'] },
  mechanism: { goal:'Entender qué hace concretamente el negocio para producir el resultado o experiencia que el cliente busca.', selectionMode:'multi', ontology:['product characteristic','process','service behavior','selection/curation','delivery/access','guidance','customization','quality control','other','unknown'] },
  proof: { goal:'Entender qué evidencia observable existe de que la compra generó valor.', selectionMode:'multi', ontology:['repeat purchase','recommendation','customer statement','behavioral use','measured result','retention','expansion','other','no evidence yet'] },
  category_tension: { goal:'Entender qué práctica habitual de la categoría perjudica, decepciona o complica al cliente.', selectionMode:'multi', ontology:['quality problem','poor service','lack of clarity','poor fit','price/value problem','inconsistency','overpromising','friction','other','unknown'] },
  brand_best_self: { goal:'Entender qué hace el negocio, en su mejor versión, que demuestra una forma distinta de trabajar.', selectionMode:'multi', ontology:['quality standard','service behavior','process discipline','selection criterion','transparency','care','expertise','reliability','other','unknown'] },
  principle: { goal:'Entender qué comportamiento o estándar no debería sacrificarse aunque el negocio creciera.', selectionMode:'multi', ontology:['quality','customer care','reliability','materials/ingredients','personalization','clarity','delivery/availability','ethics','other','unknown'] },
};

function firstJson(text=''){const start=text.indexOf('{');if(start<0)throw new Error('No JSON');let depth=0,inString=false,escape=false;for(let i=start;i<text.length;i++){const c=text[i];if(escape){escape=false;continue}if(c==='\\'){escape=true;continue}if(c==='"'){inString=!inString;continue}if(inString)continue;if(c==='{')depth++;if(c==='}'){depth--;if(depth===0)return text.slice(start,i+1)}}throw new Error('Unbalanced JSON')}

async function gemini(system,payload){const key=process.env.GEMINI_API_KEY;if(!key)throw new Error('GEMINI_API_KEY missing');const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:JSON.stringify(payload)}]}],generationConfig:{responseMimeType:'application/json',maxOutputTokens:2200}})});if(!res.ok)throw new Error(`Gemini ${res.status}: ${(await res.text()).slice(0,180)}`);const body=await res.json();const text=(body?.candidates?.[0]?.content?.parts||[]).map(p=>p?.text||'').join('');return JSON.parse(firstJson(text))}

function normalizeOptions(options,mode){if(mode==='free_text')return[];const clean=Array.isArray(options)?options.filter(x=>typeof x==='string'&&x.trim()).map(x=>x.trim()).slice(0,7):[];const lower=clean.map(x=>x.toLowerCase());if(!lower.some(x=>x.includes('otra')))clean.push('Otra cosa');if(!lower.some(x=>x.includes('no sé')||x.includes('no se')||x.includes('no lo')))clean.push('No lo sé / no lo he observado');return clean.slice(0,8)}

function validateQuestion(data,spec,categoryProfile){if(!data||typeof data.question!=='string'||data.question.length<8)throw new Error('Invalid question');if(typeof data.context_cue!=='string')data.context_cue='';data.selection_mode=spec.selectionMode;data.options=normalizeOptions(data.options,spec.selectionMode);if(spec.selectionMode!=='free_text'&&data.options.length<3)throw new Error('Too few options');const category=JSON.stringify(categoryProfile||{}).toLowerCase();const text=JSON.stringify({q:data.question,o:data.options}).toLowerCase();const foodTerms=['snack','comida','dulce','salado','hambre','antojo','ingrediente','prepararlo en casa'];const foodCategory=/alimento|comida|bebida|fruta|restaurante|snack|postre|food|beverage/.test(category);if(!foodCategory&&foodTerms.some(t=>text.includes(t)))throw new Error('Domain leakage: food vocabulary');return data}

const CONTEXT_SYSTEM=`Eres un clasificador de contexto para un Discovery de estrategia de marca para emprendedores y SMEs. Tu única tarea es entender QUÉ TIPO DE NEGOCIO/OFERTA describe el usuario. No infieras motivaciones de clientes. Devuelve JSON exacto: {"offer_kind":"physical_product|service|software|experience|mixed|other","category_label":"categoría útil en español, concreta pero no excesivamente estrecha","category_parent":"categoría amplia","business_summary":"una frase factual usando solo datos del usuario","confirmation":"frase natural: Por lo que me cuentas, entiendo que... ¿voy bien?","confidence":"high|medium|low"}. No uses jerga como B2B/B2C en confirmation. No inventes cliente, dolor, ocasión ni motivación.`;

const QUESTION_SYSTEM=`Eres el Question Personalizer de Brand Decision System. Tu trabajo NO es hacer estrategia ni inferir hechos. Recibes un strategic_intent estable, contexto factual del negocio y evidencia previa. Genera UNA pregunta en español natural y opciones de reconocimiento semánticamente compatibles. REGLAS: 1) Conserva exactamente el objetivo informacional indicado. 2) Usa categoría/oferta para impedir ejemplos absurdos; no transfieras vocabulario de otra industria. 3) Suena como conversación con un emprendedor, no formulario de marketing. 4) No fuerces nombre/producto dentro de cada oración; usa context_cue y luego pronombres naturales. 5) Las opciones deben ser plausibles PARA ESTA CATEGORÍA y este episodio; menos opciones relevantes es mejor que cobertura irrelevante. 6) No inventes que una opción ocurrió. 7) Respeta allowed_ontology; omite clases que no tengan sentido. 8) Si selection_mode=multi, la pregunta debe admitir naturalmente varias respuestas. Si free_text, options=[] y pide una frase/recuerdo concreto. 9) No uses jerga: trigger, pain, gain, JTBD, alternativa competitiva, mecanismo de valor. 10) Evita construcciones raras por interpolación. 11) Usa solo datos del payload como hechos. 12) Máximo 6 opciones sustantivas, además de Otra cosa / No lo sé. Devuelve JSON exacto: {"context_cue":"referencia breve y natural al caso actual","question":"pregunta principal","helper":"máximo una frase","options":["..."],"selection_mode":"single|multi|primary_plus_secondary|free_text","semantic_notes":["breve razón de por qué cada opción encaja en la categoría"]}`;

export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');if(req.method==='OPTIONS')return res.status(200).end();if(req.method!=='POST')return res.status(405).json({error:'Método no permitido'});if(req.query?.key!==ACCESS_KEY)return res.status(403).json({error:'Acceso denegado'});const body=req.body||{};try{if(body.action==='infer_context'){const result=await gemini(CONTEXT_SYSTEM,{business_name:body.business_name||'',offer:body.offer||'',payer_mode:body.payer_mode||'',recent_purchase:body.recent_purchase||''});return res.status(200).json(result)}if(body.action==='generate_question'){const spec=INTENTS[body.strategic_intent];if(!spec)return res.status(400).json({error:'Strategic intent inválido'});let result=await gemini(QUESTION_SYSTEM,{strategic_intent:body.strategic_intent,information_goal:spec.goal,allowed_ontology:spec.ontology,selection_mode:spec.selectionMode,business_context:body.business_context||{},category_profile:body.category_profile||{},purchase_episode:body.purchase_episode||{},known_evidence:body.known_evidence||{},respondent_vocabulary:body.respondent_vocabulary||[]});result=validateQuestion(result,spec,body.category_profile);return res.status(200).json(result)}if(body.action==='submit'){const saved=await sbInsert('discovery_validation_submissions',{respondent_name:body.respondent_name||null,respondent_email:body.respondent_email||null,business_name:body.business_name||null,form_version:'semantic_personalizer_v0.6',route_profile:body.route_profile||{},answers:body.answers||{},comprehension:body.comprehension||{},metadata:{...(body.metadata||{}),source:'vercel_semantic_v06'}});return res.status(200).json({ok:true,id:saved?.id||null})}return res.status(400).json({error:'Acción inválida'})}catch(e){console.error('[discovery-v06]',e.message);return res.status(502).json({error:'No se pudo generar la pregunta',detail:e.message})}}
